package query

import (
	"cmp"
	"fmt"
	"regexp"

	"github.com/apache/arrow-go/v18/arrow"
	"github.com/apache/arrow-go/v18/arrow/array"
	"github.com/substrait-io/substrait-go/v8/expr"
	"github.com/substrait-io/substrait-go/v8/extensions"
	"github.com/substrait-io/substrait-go/v8/plan"
)

type executionPlan struct {
	matches func(arrow.RecordBatch, int) bool
	columns []int
	names   []string
	limit   int64
}

// compilePlan consumes the locally generated Read -> Filter? -> Project? -> Fetch?
// shape. Execution derives predicates, output columns, and limits from this plan.
func compilePlan(p *plan.Plan, schema *arrow.Schema) (*executionPlan, error) {
	roots := p.GetRoots()
	if len(roots) != 1 {
		return nil, fmt.Errorf("expected one query root")
	}

	execution := &executionPlan{
		matches: func(arrow.RecordBatch, int) bool { return true },
		names:   roots[0].Names(),
		limit:   -1,
	}
	rel := roots[0].Input()

	if fetch, ok := rel.(*plan.FetchRel); ok {
		if fetch.Offset() != 0 || fetch.Count() < 0 {
			return nil, fmt.Errorf("unsupported fetch offset or count")
		}
		execution.limit = fetch.Count()
		rel = fetch.Input()
	}

	if project, ok := rel.(*plan.ProjectRel); ok {
		for _, output := range project.OutputMapping() {
			index := int(output) - int(project.Input().RecordType().FieldCount())
			if index < 0 || index >= len(project.Expressions()) {
				return nil, fmt.Errorf("unsupported projection output %d", output)
			}

			ref, ok := project.Expressions()[index].(*expr.FieldReference)
			if !ok {
				return nil, fmt.Errorf("projection must select a column")
			}
			execution.columns = append(execution.columns, referenceIndex(ref))
		}
		rel = project.Input()
	} else {
		for i := range schema.Fields() {
			execution.columns = append(execution.columns, i)
		}
	}

	if filter, ok := rel.(*plan.FilterRel); ok {
		fn, ok := filter.Condition().(*expr.ScalarFunction)
		if !ok {
			return nil, fmt.Errorf("unsupported filter expression")
		}

		matches, err := compilePredicate(fn)
		if err != nil {
			return nil, fmt.Errorf("compile predicate: %w", err)
		}
		execution.matches = matches
		rel = filter.Input()
	}

	if _, ok := rel.(*plan.NamedTableReadRel); !ok {
		return nil, fmt.Errorf("unsupported input relation %T", rel)
	}
	if len(execution.names) != len(execution.columns) {
		return nil, fmt.Errorf("output column count does not match root names")
	}
	for _, column := range execution.columns {
		if column < 0 || column >= len(schema.Fields()) {
			return nil, fmt.Errorf("output column index %d out of range", column)
		}
	}
	return execution, nil
}

func referenceIndex(ref *expr.FieldReference) int {
	return int(ref.ToProto().GetSelection().GetDirectReference().GetStructField().GetField())
}

// compilePredicate only accepts functions generated by this package. Null
// comparisons do not match; IS NULL and IS NOT NULL produce non-null booleans.
func compilePredicate(fn *expr.ScalarFunction) (func(arrow.RecordBatch, int) bool, error) {
	if fn.NArgs() == 0 {
		return nil, fmt.Errorf("predicate has no column argument")
	}
	ref, ok := fn.Arg(0).(*expr.FieldReference)
	if !ok {
		return nil, fmt.Errorf("predicate must reference a column")
	}
	field := referenceIndex(ref)

	if fn.ID().URN == regexURN && fn.Name() == "go_regexp_match" {
		literal, ok := fn.Arg(1).(*expr.PrimitiveLiteral[string])
		if !ok {
			return nil, fmt.Errorf("regex requires a string pattern")
		}

		re, err := regexp.Compile(literal.Value)
		if err != nil {
			return nil, fmt.Errorf("invalid regex: %w", err)
		}

		return func(record arrow.RecordBatch, row int) bool {
			column := record.Column(field).(*array.String)
			return !column.IsNull(row) && re.MatchString(column.Value(row))
		}, nil
	}

	if fn.ID().URN != extensions.SubstraitDefaultURNPrefix+"functions_comparison" {
		return nil, fmt.Errorf("unsupported predicate function %s", fn.ID())
	}

	switch fn.Name() {
	case "is_null":
		return func(record arrow.RecordBatch, row int) bool {
			return record.Column(field).IsNull(row)
		}, nil
	case "is_not_null":
		return func(record arrow.RecordBatch, row int) bool {
			return !record.Column(field).IsNull(row)
		}, nil
	case functionEqual, functionNotEqual, "gt", functionGTE, "lt", functionLTE:
	default:
		return nil, fmt.Errorf("unsupported comparison %q", fn.Name())
	}

	// Bind the literal once; each row reads its typed Arrow column directly.
	var order func(arrow.RecordBatch, int) int
	switch literal := fn.Arg(1).(type) {
	case *expr.PrimitiveLiteral[int64]:
		order = func(record arrow.RecordBatch, row int) int {
			return cmp.Compare(record.Column(field).(*array.Int64).Value(row), literal.Value)
		}
	case *expr.PrimitiveLiteral[int32]:
		order = func(record arrow.RecordBatch, row int) int {
			return cmp.Compare(record.Column(field).(*array.Int32).Value(row), literal.Value)
		}
	case *expr.PrimitiveLiteral[string]:
		order = func(record arrow.RecordBatch, row int) int {
			return cmp.Compare(record.Column(field).(*array.String).Value(row), literal.Value)
		}
	default:
		return nil, fmt.Errorf("unsupported comparison literal %T", literal)
	}

	return func(record arrow.RecordBatch, row int) bool {
		if record.Column(field).IsNull(row) {
			return false
		}
		return compare(fn.Name(), int64(order(record, row)), 0)
	}, nil
}

func compare(op string, left, right int64) bool {
	switch op {
	case functionEqual:
		return left == right
	case functionNotEqual:
		return left != right
	case "gt":
		return left > right
	case functionGTE:
		return left >= right
	case "lt":
		return left < right
	case functionLTE:
		return left <= right
	default:
		panic("unexpected generated comparison: " + op)
	}
}
